apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: nitin
spec:
  replicas: 3
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mahendrshinde/myweb:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

