apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    name: demo-1
spec:
  containers:
  - name: app
    image: mahendrshinde/myweb:1
    resources:
      limits:
        memory: 32Mi
        cpu: 100m
    ports:
      - containerPort: 80

  - name: db
    image: mahendrshinde/mysql-sample:employees
    resources:
      limits:
        memory: 128Mi
        cpu: 300m
    ports:
      - containerPort: 3306