apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    name: demo-1
spec:
  initContainers:
    - name: init1
      image: ubuntu
      command: ['/usr/bin/sleep', '5s']
  containers:
  - name: db
    image: mahendrshinde/mysql-sample:employees
    resources:
      limits:
        memory: 128Mi
        cpu: 300m
    ports:
      - containerPort: 3306