apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: demo-1
spec:
  containers:
  - name: app
    image: mahendrashinde/myweb:1
    resources:
      limits:
        memory: 32Mi
        cpu: 100m
    ports:
      - containerPort: 80
