apiVersion: apps/v1
kind: Deployment
metadata:
  name: app7
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app7
  template:
    metadata:
      labels:
        app: app7
    spec:
      containers:
      - name: myapp
        image: mahendrshinde/myweb:1
        # check if probe is succeeded
        # when probe fails it will restart the pod
        livenessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 80 # container port (port no on  which app is running)
          failureThreshold: 2 # Two consecutive
          periodSeconds: 10 # Run Every 10 sec
          timeoutSeconds: 5 # req should be processed within 10 secs
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
