apiVersion: apps/v1
kind: Deployment
metadata:
  name: app8
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app8
  template:
    metadata:
      labels:
        app: app8
    spec:
      containers:
      - name: myapp
        image: mahendrshinde/myweb:1
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  # clusterIP is default type
  type: ClusterIP
  selector:
    app: app8
  ports:
  - port: 80
    targetPort: 80 #pod port
