apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
spec:
  replicas: 3
  selector:
    matchLabels:
      set: app1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        set: app1
    spec:
      containers:
      - name: web
        image: mahendrshinde/myweb:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
