apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  imagePullSecrets:
    - name: myregistry
  containers:
  - name: myapp
    imagePullPolicy: Always
    image: mahendrashinde.azurecr.io/image-resizer:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
