apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    name: app3
spec:
  containers:
  - name: pod3
    image: nginx:alpine
    envFrom:
      - configMapRef:
          name: dbconfig
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
