apiVersion: v1
kind: Pod
metadata:
  name: app4
  labels:
    name: app4
spec:
  volumes:
  - name: config
    configMap:
      name: appsettings-demo
  containers:
  - name: myapp
    image: nginx:alpine
    volumeMounts:
      - mountPath: /vars
        name: config
    resources:
      limits:
        memory: "16Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
