apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-demo
data:
  appsettings.k8s.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Info",
          "System": "Debug",
          "Microsoft": "Error"
        }
      },
      "AppConfiguration": {
        "DatabaseHost": "localhost",
        "ThirdPartyAPIBaseURL" :  "https://local.somewhere.com/"
      }
    }