apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: nitin
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: nitin
spec:
  replicas: 3
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: vol1
      containers:
      - name: web
        image: nginx:alpine
        resources:  
          limits:
            cpu: "100m"
            memory: '128Mi'
        volumeMounts:
        - name: vol1
          mountPath: /data
        ports:
        - containerPort: 80